### ISSUE TITLE
macOS: go movetime / depth

### ISSUE THREAD

**Issue by twoplan** [SamuraiDangyo/Sapeli#12]
I ran some test positions with our engine. Your engine seems not to support uci command **go movetime x** or **go depth y**. In both cases Sapeli answers instantly.

```
Starting engine /Users/max/chess/Sapeli/sapeli-1.33 ...
>> uci
<< Sapeli v1.33 by Toni Helminen
<< GNU General Public License version 3; for details see `sapeli -license´
<< id name Sapeli 1.33
<< id author Toni Helminen
<< option name UCI_Chess960 type check default false
<< option name UCI_Kingofthehill type check default false
<< option name WhitePOV type check default false
<< option name AiLevel type spin default 100 min 0 max 100
<< option name GoodMovesHash type spin default 128 min 16 max 1048576
<< option name EvalHash type spin default 256 min 16 max 1048576
<< uciok
>> setoption name Hash value 128
>> setoption name Contempt value 0
>> setoption name Threads value 1
>> setoption name Cores value 1
>> setoption name Max CPUs value 1

Pos 1
1kr5/3n4/q3p2p/p2n2p1/PppB1P2/5BP1/1P2Q2P/3R2K1 w - - bm f5; id "STS(v1.0) Undermine.001"; c0 "f5=10, Be5+=2, Bf2=3, Bg4=2"; c7 "f5 Be5+ Bf2 Bg4"; c8 "10 2 3 2"; c9 "f4f5 d4e5 d4f2 f3g4";

2019-07-08T15:14:58.484144 >> isready
2019-07-08T15:14:58.484186 << readyok
2019-07-08T15:14:58.484200 >> ucinewgame
2019-07-08T15:14:58.484217 >> position fen 1kr5/3n4/q3p2p/p2n2p1/PppB1P2/5BP1/1P2Q2P/3R2K1 w - - 0 1
2019-07-08T15:14:58.484238 >> go movetime 193
2019-07-08T15:14:58.485140 << info depth 0 nodes 238 time 1 nps 238000 score cp -43 pv f4f5
2019-07-08T15:14:58.486154 << info depth 1 nodes 633 time 2 nps 316500 score cp -43 pv f4f5
2019-07-08T15:14:58.486264 << info depth 2 nodes 633 time 2 nps 316500 score cp -43 pv f4f5
2019-07-08T15:14:58.486295 << bestmove f4f5
Engine best move is correct!!
Position points earned             : 10
Total points for this theme so far : 10/10

```

```
2019-07-08T15:16:28.209173 >> go depth 4
2019-07-08T15:16:28.210099 << info depth 0 nodes 245 time 0 nps 0 score cp -43 pv f4f5
2019-07-08T15:16:28.211060 << info depth 1 nodes 627 time 1 nps 627000 score cp -43 pv f4f5
2019-07-08T15:16:28.211161 << info depth 2 nodes 627 time 1 nps 627000 score cp -43 pv f4f5
2019-07-08T15:16:28.211192 << bestmove f4f5
Engine best move is correct!!
Position points earned             : 10
Total points for this theme so far : 10/10
```

Is this a macOS issue, or didn't you implement go movetime/depth?

BTW: compiled with clang-1000.10.44.4 I get on a MacBook Air significant higher nps than yours on talkchess (no profile build):
./sapeli-1.33 -bench
...
= nodes 195978548 **mnps 6.530** time 30.010

**Comment by SamuraiDangyo** [comment]
Thanks for the feedback!
Uci support is pretty minimal on Sapeli. But these 2 were simple to add:
Should work ok!
This branch+master contains the code: https://github.com/SamuraiDangyo/Sapeli/tree/1.34

`Sapeli v1.34 by Toni Helminen
GNU General Public License version 3; for details see `sapeli -license´
go movetime 2000
info depth 0 nodes 40 time 0 nps 0 score cp 56 pv e2e3
info depth 1 nodes 248 time 2 nps 124000 score cp 0 pv e2e3
info depth 2 nodes 2754 time 9 nps 306000 score cp 40 pv d2d4
info depth 3 nodes 8855 time 23 nps 385000 score cp 0 pv c2c3
info depth 4 nodes 42316 time 80 nps 528950 score cp 18 pv d2d4
info depth 5 nodes 148267 time 206 nps 719742 score cp 8 pv b1c3
info depth 6 nodes 335418 time 377 nps 889702 score cp 20 pv e2e4
info depth 7 nodes 1038700 time 798 nps 1301629 score cp 14 pv e2e4
info depth 8 nodes 3539640 time 2001 nps 1768935 score cp 14 pv e2e4
bestmove e2e4

go depth 8
info depth 0 nodes 40 time 0 nps 0 score cp 56 pv e2e3
info depth 1 nodes 144 time 1 nps 144000 score cp 0 pv e2e3
info depth 2 nodes 1591 time 1 nps 1591000 score cp 40 pv d2d4
info depth 3 nodes 3800 time 2 nps 1900000 score cp 0 pv d2d4
info depth 4 nodes 15827 time 9 nps 1758555 score cp 18 pv d2d4
info depth 5 nodes 63498 time 24 nps 2645750 score cp 14 pv b1c3
info depth 6 nodes 136499 time 49 nps 2785693 score cp 15 pv b1c3
info depth 7 nodes 778239 time 309 nps 2518572 score cp 10 pv e2e4
info depth 8 nodes 2112449 time 810 nps 2607961 score cp 10 pv e2e4
info depth 9 nodes 2112449 time 810 nps 2607961 score cp 10 pv e2e4
bestmove e2e4

go movetime 500
info depth 0 nodes 40 time 0 nps 0 score cp 56 pv e2e3
info depth 1 nodes 140 time 0 nps 0 score cp 0 pv e2e3
info depth 2 nodes 1411 time 1 nps 1411000 score cp 40 pv d2d4
info depth 3 nodes 3586 time 2 nps 1793000 score cp 0 pv d2d4
info depth 4 nodes 21130 time 10 nps 2113000 score cp 22 pv b1c3
info depth 5 nodes 57460 time 20 nps 2873000 score cp 20 pv b1c3
info depth 6 nodes 223196 time 84 nps 2657095 score cp 18 pv e2e4
info depth 7 nodes 622038 time 225 nps 2764613 score cp 14 pv b1c3
info depth 8 nodes 1254007 time 501 nps 2503007 score cp 14 pv b1c3
bestmove b1c3

go depth 5
info depth 0 nodes 40 time 0 nps 0 score cp 56 pv e2e3
info depth 1 nodes 140 time 1 nps 140000 score cp 0 pv e2e3
info depth 2 nodes 1402 time 1 nps 1402000 score cp 40 pv d2d4
info depth 3 nodes 3452 time 2 nps 1726000 score cp 0 pv d2d4
info depth 4 nodes 15537 time 8 nps 1942125 score cp 23 pv b1c3
info depth 5 nodes 50883 time 18 nps 2826833 score cp 14 pv b1c3
info depth 6 nodes 50883 time 18 nps 2826833 score cp 14 pv b1c3
bestmove b1c3
`

Your clang builds seems fine. Your computer/cpu is much faster than mine. It's great to see Sapeli getting so high mnps on single CPU!

**Comment by twoplan** [comment]
Great, thanks a lot Toni!
